<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-09AO3Q3" ignored="0" name="Default test" tests="8" failures="1" timestamp="2022-02-15T12:13:20 CET" time="18.09" errors="0">
  <testcase name="runScenario" time="8.649" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="8.789" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="8.789" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="8.849" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="8.91" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="Detected same images for al products error for login with problem User expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Detected same images for al products error for login with problem User expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at parallel.LoginPageSteps.user_login_is_successful_but_found_problems_after_login_with_Problem_user_credentials_for_scenario(LoginPageSteps.java:66)
at âœ½.User Login is successful but found problems after login with Problem user credentials for scenario "Problem User"(file:///E:/MobileAutomation/seleniumworkspace/SauceUIPOMDemo/src/test/resources/parallel/Login.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="13.246" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="13.951" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="15.922" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Default test -->
